# Generated by Django 5.2.7 on 2026-02-25 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'category_type')},
        ),
    ]
