# Generated by Django 5.0.14 on 2026-02-24 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description shown above the download button'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional PDF documentation for this project', null=True, upload_to='projects/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
