# Generated by Django 5.2.8 on 2025-12-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
