# Generated by Django 5.0.14 on 2026-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the note title', max_length=200)),
                ('content', models.TextField(help_text='Enter the note content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
